name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: chaplyk/docker-compose-remote-action@v1.1
      with:
        ssh_host: 41.59.227.94
        ssh_port: 1010
        ssh_user: ${{ secrets.HPRS_STAGE_SSH_USER }}
        ssh_key: ${{ secrets.HPRS_STAGE_SSH_PRIVATE_KEY }}
        compose_file: docker-compose.yml
        pull: true
        build: true

